name: Deploy Laravel Application

on:
  push:
    branches:
      - main # Ou 'master', dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 4. Deploy no Servidor via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /caminho/para/seu/projeto/no/servidor
            git pull origin main
            # Na primeira vez, você precisará rodar: ./init-letsencrypt.sh
            docker-compose down # Garante que os containers antigos sejam removidos
            docker-compose up -d --build # Sobe a nova versão
            
            # # Instala as dependências do Composer dentro do container
            # # --no-interaction: Não faz perguntas interativas
            # # --optimize-autoloader: Otimiza o autoloader para produção
            # docker exec simple_php_app composer install --no-interaction --optimize-autoloader --no-dev
            # 
            # # Os comandos artisan continuam os mesmos
            # docker exec simple_php_app php artisan migrate --force
            # docker exec simple_php_app php artisan config:cache
            # docker exec simple_php_app php artisan route:cache
            # docker exec simple_php_app php artisan view:cache