services:
  # Serviço da Aplicação (PHP)
  app:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY_NAME}:latest
    container_name: simple_php_app
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db

  # Serviço do Web Server (Nginx)
  webserver:
    image: nginx:alpine
    container_name: simple_nginx_web
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: simple_mysql_db
    restart: unless-stopped
    ports:
      - "33069:3306" # Porta para conectar com um cliente de DB local
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local