# docker-compose.yml

version: '3.8'

services:
  # Serviço 1: PHP
  app:
    image: php:8.2-fpm # Usamos a imagem FPM, que é otimizada para trabalhar com Nginx
    container_name: php_app
    volumes:
      - ./src:/var/www/html # Mapeia a pasta 'src' local para dentro do contêiner
    networks:
      - app-network

  # Serviço 2: Servidor Web Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
      - "8080:80" # Expõe a porta 80 do Nginx na porta 8080 da sua máquina
    volumes:
      - ./src:/var/www/html # Compartilha o mesmo código com o PHP
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Usa nossa configuração do Nginx
    depends_on:
      - app # Garante que o Nginx só inicie depois do serviço 'app' (PHP)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
